/// <reference types="long" />
import { proto } from "@adiwajshing/baileys";
import { Auth } from "./Auth";
export declare class Chat {
    DBId: number;
    DBAuth: Auth;
    id: string;
    messages?: proto.IHistorySyncMsg[] | null;
    newJid?: string | null;
    oldJid?: string | null;
    lastMsgTimestamp?: number | Long | null;
    unreadCount?: number | null;
    readOnly?: boolean | null;
    endOfHistoryTransfer?: boolean | null;
    ephemeralExpiration?: number | null;
    ephemeralSettingTimestamp?: number | Long | null;
    endOfHistoryTransferType?: proto.Conversation.EndOfHistoryTransferType | null;
    conversationTimestamp?: number | Long | null;
    name?: string | null;
    pHash?: string | null;
    notSpam?: boolean | null;
    archived?: boolean | null;
    disappearingMode?: proto.IDisappearingMode | null;
    unreadMentionCount?: number | null;
    markedAsUnread?: boolean | null;
    participant?: proto.IGroupParticipant[] | null;
    tcToken?: Uint8Array | null;
    tcTokenTimestamp?: number | Long | null;
    contactPrimaryIdentityKey?: Uint8Array | null;
    pinned?: number | null;
    muteEndTime?: number | Long | null;
    wallpaper?: proto.IWallpaperSettings | null;
    mediaVisibility?: proto.MediaVisibility | null;
    tcTokenSenderTimestamp?: number | Long | null;
    suspended?: boolean | null;
    terminated?: boolean | null;
    createdAt?: number | Long | null;
    createdBy?: string | null;
    description?: string | null;
    support?: boolean | null;
    isParentGroup?: boolean | null;
    isDefaultSubgroup?: boolean | null;
    parentGroupId?: string | null;
    displayName?: string | null;
    pnJid?: string | null;
    selfMasked?: boolean | null;
    mute?: number | null;
    pin?: number | null;
    archive?: boolean;
}
